// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://occpeffsghdsnappopzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jY3BlZmZzZ2hkc25hcHBvcHpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MzAyNjYsImV4cCI6MjA2NDAwNjI2Nn0.kerNpb_EAjG75CXRvOlkA75J5b6hrenT849boTpF_ok";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);